-- =============================================================================
-- 0013_seed_unidasul_opportunities.sql — Tenant Unidasul + admin + 64 opps (Workshop I)
-- =============================================================================
-- Cria, para o cliente piloto UNIDASUL:
--   • Tenant `unidasul` (UUID fixo 55551da5-...)
--   • Auth user admin.unidasul@pswdigital.com.br / 0123456789 (UUID fixo bbbbbbbb-...)
--   • Identidade email no auth.identities (necessário para login funcionar)
--   • Profile vinculado é criado AUTOMATICAMENTE pelo trigger handle_new_user
--     (0001_init.sql) — ele lê tenant_id do raw_app_meta_data
--   • As 64 oportunidades reais do Workshop I (fonte do const DATA do
--     _giba_wsi-dashboard.html), na shape v0.2 (criterios/beneficios/fte_horas).
--
-- WRITE-ONLY MODE — aplicar MANUALMENTE no Supabase Cloud SQL Editor.
--   NÃO rodar `supabase db push` nem `supabase migration up`.
--   Handoff: .planning/phases/15-seed-dados-workshop/15-01-MIGRATION-HANDOFF.md
--
-- Pré-requisitos: 0001..0012 aplicadas (schema v0.2 completo: enums frequency_bucket
--   /fte_bucket, colunas criterios/beneficios/fte_horas/fonte, rpa_score GENERATED,
--   view opportunities_with_score, trigger seq_id, trigger handle_new_user).
--
-- IDEMPOTENTE: `on conflict` no tenant/user + GUARD POR COUNT no INSERT das 64
--   (D-06: se a Unidasul já tem oportunidades, pula o insert via raise notice —
--   seq_id é trigger-assigned, sem chave natural, então ON CONFLICT não protege).
--
-- NUNCA inserimos seq_id (trigger), rpa_score (GENERATED), score/priority_level
--   (view opportunities_with_score) — docs/PROJETO.md §3. Inserir aborta o statement.
-- =============================================================================

set session characteristics as transaction read write;
set default_transaction_read_only = off;

-- -----------------------------------------------------------------------------
-- 1. Tenant Unidasul (espelha 0002 §21-23) — UUID fixo próprio, distinto de
--    FGCoop (11111111-...) e do tenant de teste Acme (22222222-...).
-- -----------------------------------------------------------------------------
insert into tenants (id, name, slug)
values ('55551da5-0000-0000-0000-000000000001'::uuid, 'Unidasul', 'unidasul')
on conflict (slug) do nothing;

-- -----------------------------------------------------------------------------
-- 2. Auth user + identity do admin Unidasul (espelha 0002 §28-124).
--    UUID fixo próprio (bbbbbbbb-...), distinto do admin FGCoop (aaaaaaaa-...).
-- -----------------------------------------------------------------------------
do $$
declare
  v_user_id   uuid := 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid;
  v_tenant_id uuid := '55551da5-0000-0000-0000-000000000001'::uuid;
  v_email     text := 'admin.unidasul@pswdigital.com.br';
  v_password  text := '0123456789';
  v_full_name text := 'Admin Unidasul';
begin
  -- 2a. auth.users ----------------------------------------------------------
  -- handle_new_user trigger dispara e cria o profile a partir do tenant_id em
  -- raw_app_meta_data. email já confirmado (não precisa link).
  if not exists (select 1 from auth.users where id = v_user_id) then
    insert into auth.users (
      instance_id,
      id,
      aud,
      role,
      email,
      encrypted_password,
      email_confirmed_at,
      raw_app_meta_data,
      raw_user_meta_data,
      created_at,
      updated_at,
      confirmation_token,
      email_change,
      email_change_token_new,
      recovery_token
    ) values (
      '00000000-0000-0000-0000-000000000000'::uuid,
      v_user_id,
      'authenticated',
      'authenticated',
      v_email,
      crypt(v_password, gen_salt('bf')),
      now(),
      jsonb_build_object(
        'provider',  'email',
        'providers', jsonb_build_array('email'),
        'tenant_id', v_tenant_id::text           -- lido pelo trigger handle_new_user
      ),
      jsonb_build_object(
        'full_name', v_full_name,
        'tenant_id', v_tenant_id::text           -- redundância de segurança
      ),
      now(),
      now(),
      '',
      '',
      '',
      ''
    );
  end if;

  -- 2b. auth.identities -----------------------------------------------------
  -- Sem essa linha, login com email/senha falha em versões recentes do Supabase.
  if not exists (
    select 1 from auth.identities
    where provider = 'email' and user_id = v_user_id
  ) then
    insert into auth.identities (
      id,
      user_id,
      provider_id,
      identity_data,
      provider,
      last_sign_in_at,
      created_at,
      updated_at
    ) values (
      gen_random_uuid(),
      v_user_id,
      v_user_id::text,
      jsonb_build_object(
        'sub',            v_user_id::text,
        'email',          v_email,
        'email_verified', true,
        'phone_verified', false
      ),
      'email',
      now(),
      now(),
      now()
    );
  end if;

  -- 2c. profile (fallback caso o trigger não tenha rodado) + garante role.
  if not exists (select 1 from profiles where id = v_user_id) then
    insert into profiles (id, tenant_id, email, full_name, role)
    values (v_user_id, v_tenant_id, v_email, v_full_name, 'tenant_admin')
    on conflict (id) do nothing;
  else
    update profiles set role = 'tenant_admin'
    where id = v_user_id and role <> 'tenant_admin';
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- 3. Sanity check (espelha 0003 §15-23): tenant e admin precisam existir.
-- -----------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from tenants where id = '55551da5-0000-0000-0000-000000000001'::uuid) then
    raise exception 'Tenant Unidasul não encontrado. Verifique o Bloco 1 desta migration.';
  end if;
  if not exists (select 1 from auth.users where id = 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid) then
    raise exception 'Admin Unidasul não encontrado. Verifique o Bloco 2 desta migration.';
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- 4. Guard de idempotência por count (D-06) + INSERT das 64 oportunidades.
--    Colunas enumeradas como 0003. NÃO enumerar seq_id/rpa_score/score/
--    priority_level (trigger/GENERATED/view). criterios em sim/nao/parcial
--    (minúsculo, sem acento); beneficios 1–5; tempo=frequency_bucket; fte=fte_bucket.
-- -----------------------------------------------------------------------------
do $$
begin
  if (select count(*) from opportunities where tenant_id = '55551da5-0000-0000-0000-000000000001'::uuid) > 0 then
    raise notice 'Unidasul já tem oportunidades — pulando insert (idempotência D-06).';
  else
    insert into opportunities (
      tenant_id, source, solicitante, email, area, subarea, processo,
      fonte, tipo_processo, frequencia, volume_medio, tempo_execucao, num_pessoas,
      ferramenta, esforco, complexidade, tempo, objetivo, fte, fte_horas,
      criterios, beneficios, beneficio_qualitativo, status, created_by
    ) values
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Moises', 'Moisesabrahanmirandaleon@gmail.com', 'TI', 'Service Desk', 'Ja automatize meus processos', 'Workshop I', array['Tecnologia da Informação (TI)', 'Atendimento', 'Suporte e Apoio']::text[], 'Diário', 'Acima de 20 Vezes', '1 dia (Até 8 horas)', 'De 5 a 8 pessoas', 'rpa'::automation_tool, 'alto'::effort_level, 'baixo'::complexity_level, 'diario'::frequency_bucket, 5, 'muito_alto'::fte_bucket, 1144, '{"causaReclamacoes":"nao","totalmenteManual":"parcial","regrasClaras":"sim","decisaoHumana":"sim","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":5,"produtividade":5,"qualidadeDados":5,"reducaoCustos":5,"reducaoRetrabalho":5,"compliance":5,"objetivosEstrategicos":5}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Rafaela Pohlmann', 'rafaela.silva@unidasul.com.br', 'Saude Ocupacional', 'SESMT', 'Lançamento de ASO', 'Workshop I', array['Saúde', 'Operacional', 'Recursos Humanos']::text[], 'Diário', 'Acima de 20 Vezes', 'Recebo esse documento durante o dia todo, enquanto chego eu estou lançando', 'De 2 a 4 pessoas', 'rpa'::automation_tool, 'alto'::effort_level, 'baixo'::complexity_level, 'diario'::frequency_bucket, 5, 'muito_alto'::fte_bucket, 231, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"nao","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"nao","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":5,"produtividade":5,"qualidadeDados":5,"reducaoCustos":5,"reducaoRetrabalho":5,"compliance":5,"objetivosEstrategicos":5}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Bruna Rodrigues de Matos', 'bruna.rodrigues@unidasul.com.br', 'RH', 'Treinamento e Desenvolvimento', 'Lançamento listas de treinamentos', 'Workshop I', array['Recursos Humanos', 'Operacional', 'Arquivo']::text[], 'Diário', 'Acima de 20 Vezes', '1 Semana (Até 40 horas)', 'De 2 a 4 pessoas', 'rpa'::automation_tool, 'alto'::effort_level, 'baixo'::complexity_level, 'diario'::frequency_bucket, 4, 'muito_alto'::fte_bucket, 2640, '{"causaReclamacoes":"sim","totalmenteManual":"parcial","regrasClaras":"sim","decisaoHumana":"nao","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":5,"produtividade":5,"qualidadeDados":5,"reducaoCustos":3,"reducaoRetrabalho":3,"compliance":3,"objetivosEstrategicos":3}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Sheila Raupp Bauer', 'Sheila.bauer@unidasul.com.br', 'Controladoria', 'Fiscal', 'Conciliação fiscal x contabilidade', 'Workshop I', array['Fiscal', 'Operacional', 'Contablidade']::text[], 'Diário', 'Acima de 20 Vezes', '1 Quinzena (Até 80 horas)', 'De 2 a 4 pessoas', 'rpa'::automation_tool, 'alto'::effort_level, 'baixo'::complexity_level, 'diario'::frequency_bucket, 4, 'muito_alto'::fte_bucket, 5280, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"sim","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":4,"eliminacaoErros":4,"produtividade":4,"qualidadeDados":4,"reducaoCustos":3,"reducaoRetrabalho":5,"compliance":5,"objetivosEstrategicos":5}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Roberto', 'Roberto.rieth@unidasul.com.br', 'Departamento pessoal', 'Departamento pessoal', 'Cálculo de Rescisões', 'Workshop I', array['Recursos Humanos', 'Operacional', 'Financeiro']::text[], 'Diário', 'Acima de 20 Vezes', 'De 3 a 4 horas', 'De 5 a 8 pessoas', 'rpa'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'diario'::frequency_bucket, 5, 'muito_alto'::fte_bucket, 500.5, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"nao","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":4,"eliminacaoErros":4,"produtividade":5,"qualidadeDados":5,"reducaoCustos":4,"reducaoRetrabalho":5,"compliance":5,"objetivosEstrategicos":5}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Roberto', 'Roberto.rieth@unidasul.com.br', 'Saude Ocupacional', 'Saúde Ocupacional', 'Informações ASOs', 'Workshop I', array['Operacional', 'Recursos Humanos', 'Financeiro']::text[], 'Diário', 'Acima de 20 Vezes', 'De 3 a 4 horas', 'De 2 a 4 pessoas', 'rpa'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'diario'::frequency_bucket, 5, 'muito_alto'::fte_bucket, 231, '{"causaReclamacoes":"sim","totalmenteManual":"parcial","regrasClaras":"sim","decisaoHumana":"nao","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"nao","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":5,"produtividade":5,"qualidadeDados":5,"reducaoCustos":5,"reducaoRetrabalho":5,"compliance":5,"objetivosEstrategicos":5}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Cleonir', 'cleonir.lopes@unidasul.com.br', 'Controladoria', 'Fiscal', 'Conferência Fiscal', 'Workshop I', array['Operacional', 'Contablidade', 'Fiscal']::text[], 'Diário', 'Acima de 20 Vezes', '1 Quinzena (Até 80 horas)', 'De 2 a 4 pessoas', 'rpa'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'diario'::frequency_bucket, 5, 'muito_alto'::fte_bucket, 5280, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"nao","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":5,"produtividade":5,"qualidadeDados":5,"reducaoCustos":5,"reducaoRetrabalho":5,"compliance":5,"objetivosEstrategicos":5}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Elisiane', 'elisiane.pedroso@unidasul.com.br', 'Financeiro', 'Contas  a Receber', 'Avaliação de clientes - Serasa', 'Workshop I', array['Operacional', 'Financeiro', 'Comercial / Vendas']::text[], 'Diário', 'Acima de 20 Vezes', 'De 3 a 4 horas', 'De 2 a 4 pessoas', 'ambos'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'diario'::frequency_bucket, 5, 'muito_alto'::fte_bucket, 231, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"nao","decisaoHumana":"sim","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":3,"produtividade":5,"qualidadeDados":5,"reducaoCustos":3,"reducaoRetrabalho":5,"compliance":5,"objetivosEstrategicos":5}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Cleonir', 'cleonir.lopes@unidasul.com.br', 'Controladoria', 'Fiscal', 'Apuração Prévia de ICMS', 'Workshop I', array['Operacional', 'Fiscal', 'Contablidade']::text[], 'Diário', '1 a 3 Vezes', 'De 3 a 4 horas', '1 Pessoa', 'rpa'::automation_tool, 'alto'::effort_level, 'baixo'::complexity_level, 'diario'::frequency_bucket, 5, 'medio'::fte_bucket, 77, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"nao","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"nao"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":5,"produtividade":5,"qualidadeDados":5,"reducaoCustos":3,"reducaoRetrabalho":5,"compliance":5,"objetivosEstrategicos":5}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Eduarda Rocha', 'eduarda.rocha@unidasul.com.br', 'Financeiro', 'Contas a Receber', 'Avaliação de clientes - Serasa', 'Workshop I', array['Financeiro', 'Operacional', 'Comercial / Vendas']::text[], 'Diário', '9 a 15 Vezes', 'De 3 a 4 horas', 'De 2 a 4 pessoas', 'ambos'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'diario'::frequency_bucket, 4, 'muito_alto'::fte_bucket, 231, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"nao","decisaoHumana":"sim","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":3,"produtividade":4,"qualidadeDados":5,"reducaoCustos":3,"reducaoRetrabalho":2,"compliance":3,"objetivosEstrategicos":4}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Jefferson', 'jefferson.paulos@unidasul.com.br', 'Central de cadastros', 'Cadastro/Materiais', 'Descrição de Materiais', 'Workshop I', array['Operacional', 'Cadastro', 'Comercial / Vendas']::text[], 'Diário', 'Acima de 20 Vezes', '1 dia (Até 8 horas)', 'De 2 a 4 pessoas', 'rpa'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'diario'::frequency_bucket, 4, 'muito_alto'::fte_bucket, 528, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"sim","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":4,"eliminacaoErros":4,"produtividade":4,"qualidadeDados":5,"reducaoCustos":3,"reducaoRetrabalho":5,"compliance":4,"objetivosEstrategicos":4}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Lislaine', 'lislaine.teresinha@unidasul.com.br', 'Financiro', 'Tesouraria', 'Depósito numerário', 'Workshop I', array['Operacional', 'Financeiro', 'Lojas']::text[], 'Diário', '1 a 3 Vezes', 'De 1 a 2 horas', '1 financeiro e todas as tesoureiras das lojas', 'rpa'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'diario'::frequency_bucket, 4, 'muito_alto'::fte_bucket, 264, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"sim","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":5,"produtividade":5,"qualidadeDados":5,"reducaoCustos":2,"reducaoRetrabalho":5,"compliance":2,"objetivosEstrategicos":5}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Luana Bach', 'luana.deolinda@unidasul.com.br', 'Controladoria', 'Contabilidade', 'Integração contábil sapiensxsap', 'Workshop I', array['Contablidade', 'Financeiro', 'Fiscal']::text[], 'Diário', '4 a 8 Vezes', 'De 1 a 2 horas', '1 Pessoa', 'rpa'::automation_tool, 'alto'::effort_level, 'baixo'::complexity_level, 'diario'::frequency_bucket, 5, 'baixo'::fte_bucket, 33, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"nao","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":3,"produtividade":5,"qualidadeDados":5,"reducaoCustos":3,"reducaoRetrabalho":5,"compliance":5,"objetivosEstrategicos":5}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Bruna Rodrigues de Matos', 'Bruna.rodrigues@unidasul.com.br', 'Segurança do Trabalho', 'Treinamento e Desenvolvimento', 'Validação certificados de NRs', 'Workshop I', array['Recursos Humanos', 'Operacional', 'Segurança do Trabalho']::text[], 'Diário', '1 a 3 Vezes', 'De 1 a 2 horas', 'De 2 a 4 pessoas', 'rpa'::automation_tool, 'alto'::effort_level, 'baixo'::complexity_level, 'diario'::frequency_bucket, 4, 'medio'::fte_bucket, 99, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"nao","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":3,"produtividade":4,"qualidadeDados":4,"reducaoCustos":4,"reducaoRetrabalho":3,"compliance":3,"objetivosEstrategicos":4}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Cátia Silva', 'catia.silva@unidasul.com.br', 'Contabilidade', 'Movimento de Caixa', 'Importação depósito recicladoras', 'Workshop I', array['Operacional', 'Contablidade', 'Financeiro']::text[], 'Diário', '1 a 3 Vezes', 'De 1 a 2 horas', '1 Pessoa', 'rpa'::automation_tool, 'alto'::effort_level, 'baixo'::complexity_level, 'diario'::frequency_bucket, 5, 'baixo'::fte_bucket, 33, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"nao","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":5,"produtividade":5,"qualidadeDados":5,"reducaoCustos":3,"reducaoRetrabalho":5,"compliance":5,"objetivosEstrategicos":5}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Augusto Conrado souza', 'augusto.souza@unidasul.com.br', 'SESMT', 'Sesmt', 'Cadastro de acidentes de trabalho', 'Workshop I', array['Operacional', 'Jurídico', 'SESMT']::text[], 'Diário', '1 a 3 Vezes', 'Cada caso tem evolução, prazo correto deve ser todo processo finalizado em 24h, excessões pode exceder', 'Equipe SESMT, acidente, gestão da filial', 'ambos'::automation_tool, 'alto'::effort_level, 'alto'::complexity_level, 'diario'::frequency_bucket, 5, 'muito_alto'::fte_bucket, 4224, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"sim","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"nao","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":5,"produtividade":5,"qualidadeDados":5,"reducaoCustos":4,"reducaoRetrabalho":5,"compliance":5,"objetivosEstrategicos":5}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Roberto', 'Robertorieth@hotmail.com', 'DP', 'DP', 'Admissão', 'Workshop I', array['Operacional', 'Recursos Humanos', 'Financeiro']::text[], 'Diário', 'Acima de 20 Vezes', 'De 3 a 4 horas', 'De 5 a 8 pessoas', 'rpa'::automation_tool, 'alto'::effort_level, 'alto'::complexity_level, 'diario'::frequency_bucket, 5, 'muito_alto'::fte_bucket, 500.5, '{"causaReclamacoes":"sim","totalmenteManual":"parcial","regrasClaras":"sim","decisaoHumana":"sim","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":5,"produtividade":5,"qualidadeDados":5,"reducaoCustos":5,"reducaoRetrabalho":5,"compliance":5,"objetivosEstrategicos":5}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Quélita Leal', 'quelita.leal@unidasul.com.br', 'Saúde', 'Pessoas e Cultura', 'RAI( CAT)', 'Workshop I', array['Operacional', 'Recursos Humanos', 'Atendimento']::text[], 'Diário', '9 a 15 Vezes', '24 horas úteis', 'De 5 a 8 pessoas', 'ambos'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'diario'::frequency_bucket, 3, 'muito_alto'::fte_bucket, 3432, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"sim","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"nao","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":3,"eliminacaoErros":2,"produtividade":3,"qualidadeDados":4,"reducaoCustos":3,"reducaoRetrabalho":4,"compliance":3,"objetivosEstrategicos":4}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Cleonir dos Santos Lopes', 'cleonir.lopes@unidasul.com.br', 'Controladoria', 'Fiscal', 'Validação Matrix x Filial', 'Workshop I', array['Operacional', 'Compliance', 'Fiscal']::text[], 'Semanal', '1 a 3 Vezes', '1 dia (Até 8 horas)', 'De 2 a 4 pessoas', 'rpa'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'semanal'::frequency_bucket, 5, 'alto'::fte_bucket, 103.2, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"nao","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":5,"produtividade":5,"qualidadeDados":5,"reducaoCustos":5,"reducaoRetrabalho":5,"compliance":5,"objetivosEstrategicos":5}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Cleonir', 'cleonir.lopes@unidasul.com.br', 'Controladoria', 'Fiscal', 'Relatórios de Conciliação', 'Workshop I', array['Operacional', 'Compliance', 'Fiscal']::text[], 'Semanal', '1 a 3 Vezes', '12hrs', 'De 2 a 4 pessoas', 'rpa'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'semanal'::frequency_bucket, 5, 'alto'::fte_bucket, 154.8, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"nao","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":5,"produtividade":5,"qualidadeDados":5,"reducaoCustos":5,"reducaoRetrabalho":5,"compliance":5,"objetivosEstrategicos":5}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Luana Bach', 'luana.deolinda@unidasul.com.br', 'Controladoria', 'Contabilidade', 'Compensação automática de conciliação', 'Workshop I', array['Operacional', 'Contablidade', 'Compliance']::text[], 'Diário', '1 a 3 Vezes', 'De 1 a 2 horas', 'De 2 a 4 pessoas', 'rpa'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'diario'::frequency_bucket, 5, 'medio'::fte_bucket, 99, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"nao","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":5,"produtividade":5,"qualidadeDados":5,"reducaoCustos":5,"reducaoRetrabalho":5,"compliance":5,"objetivosEstrategicos":5}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Bruna Rodrigues de Matos', 'Bruna.rodrigues@unidasul.com.br', 'Recursos Humanos', 'Treinamento e Desenvolvimento', 'Agenda de treinamentos', 'Workshop I', array['Recursos Humanos', 'Operacional', 'Treinamento']::text[], 'Semanal', '1 a 3 Vezes', 'De 3 a 4 horas', 'De 2 a 4 pessoas', 'rpa'::automation_tool, 'alto'::effort_level, 'baixo'::complexity_level, 'semanal'::frequency_bucket, 4, 'medio'::fte_bucket, 45.1, '{"causaReclamacoes":"sim","totalmenteManual":"parcial","regrasClaras":"sim","decisaoHumana":"nao","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":4,"produtividade":5,"qualidadeDados":4,"reducaoCustos":3,"reducaoRetrabalho":3,"compliance":3,"objetivosEstrategicos":3}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Bruna Rodrigues de Matos', 'Bruna.rodrigues@unidasul.com.br', 'RH', 'Treinamento', 'Atualização de usuários na Smartleader', 'Workshop I', array['Recursos Humanos', 'Operacional', 'Treinamento']::text[], 'Diário', '1 a 3 Vezes', 'De 1 a 2 horas', '1 Pessoa', 'rpa'::automation_tool, 'alto'::effort_level, 'baixo'::complexity_level, 'diario'::frequency_bucket, 4, 'baixo'::fte_bucket, 33, '{"causaReclamacoes":"sim","totalmenteManual":"parcial","regrasClaras":"sim","decisaoHumana":"nao","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":3,"produtividade":3,"qualidadeDados":5,"reducaoCustos":2,"reducaoRetrabalho":3,"compliance":3,"objetivosEstrategicos":4}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Julio', 'Julio.goncalves@unidasul.com.br', 'SESMT', 'Segurança do Trabalho', 'Inspeções- processo de Cipa', 'Workshop I', array['Operacional', 'Logística e Distribuição', 'Inspeção']::text[], 'Diário', '9 a 15 Vezes', '1 dia (Até 8 horas)', 'De 2 a 4 pessoas', 'rpa'::automation_tool, 'alto'::effort_level, 'alto'::complexity_level, 'diario'::frequency_bucket, 4, 'muito_alto'::fte_bucket, 528, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"sim","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":4,"eliminacaoErros":4,"produtividade":3,"qualidadeDados":4,"reducaoCustos":3,"reducaoRetrabalho":4,"compliance":3,"objetivosEstrategicos":4}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Jefferson', 'jefferson.paulos@unidasul.com.br', 'Central de cadastros', 'Cadastro', 'Ajustes Dados basicos de cadastros de clientes e fornecedores', 'Workshop I', array['Operacional', 'Cadastro clientes', 'Financeiro']::text[], 'Diário', 'Acima de 20 Vezes', '1 dia (Até 8 horas)', 'De 2 a 4 pessoas', 'ambos'::automation_tool, 'alto'::effort_level, 'alto'::complexity_level, 'diario'::frequency_bucket, 4, 'muito_alto'::fte_bucket, 528, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"sim","padronizacaoDocs":"nao","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":4,"eliminacaoErros":5,"produtividade":5,"qualidadeDados":5,"reducaoCustos":3,"reducaoRetrabalho":4,"compliance":3,"objetivosEstrategicos":4}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Cleonir', 'cleonir.lopes@unidasul.com.br', 'Controladoria', 'Fiscal', 'Planilha de Fechamento', 'Workshop I', array['Operacional', 'Contablidade', 'Fiscal']::text[], 'Semanal', '1 a 3 Vezes', '1 Quinzena (Até 80 horas)', 'De 2 a 4 pessoas', 'rpa'::automation_tool, 'alto'::effort_level, 'alto'::complexity_level, 'semanal'::frequency_bucket, 5, 'muito_alto'::fte_bucket, 1032, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"sim","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":5,"produtividade":5,"qualidadeDados":5,"reducaoCustos":5,"reducaoRetrabalho":5,"compliance":5,"objetivosEstrategicos":5}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Cátia Silva', 'catia.silva@unidasul.com.br', 'Contabilidade', 'Movimento de Caixa', 'Conferência venda', 'Workshop I', array['Contablidade', 'Operacional', 'Tecnologia da Informação (TI)']::text[], 'Diário', 'Acima de 20 Vezes', 'De 1 a 2 horas', 'De 2 a 4 pessoas', 'rpa'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'diario'::frequency_bucket, 4, 'medio'::fte_bucket, 99, '{"causaReclamacoes":"sim","totalmenteManual":"parcial","regrasClaras":"sim","decisaoHumana":"nao","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":4,"eliminacaoErros":4,"produtividade":4,"qualidadeDados":4,"reducaoCustos":3,"reducaoRetrabalho":4,"compliance":4,"objetivosEstrategicos":4}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Janaína Leandro', 'Janaína.tamara@unidasul.com.br', 'Controladoria', 'Controle & gestão', 'importação títulos verba', 'Workshop I', array['Operacional', 'Financeiro', 'Contablidade']::text[], 'Diário', '1 a 3 Vezes', 'De 1 a 2 horas', 'De 2 a 4 pessoas', 'rpa'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'diario'::frequency_bucket, 4, 'medio'::fte_bucket, 99, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"nao","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":4,"eliminacaoErros":4,"produtividade":4,"qualidadeDados":4,"reducaoCustos":3,"reducaoRetrabalho":4,"compliance":4,"objetivosEstrategicos":4}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Sheila Raupp Bauer', 'Sheila.bauer@unidasul.com.br', 'Contabilidade', 'Movimento de caixa', 'Importação relatórios de recicladora', 'Workshop I', array['Operacional', 'Contablidade', 'Financeiro']::text[], 'Diário', '1 a 3 Vezes', 'De 3 a 4 horas', '1 Pessoa', 'rpa'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'diario'::frequency_bucket, 4, 'medio'::fte_bucket, 77, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"sim","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":4,"eliminacaoErros":3,"produtividade":5,"qualidadeDados":4,"reducaoCustos":3,"reducaoRetrabalho":4,"compliance":4,"objetivosEstrategicos":5}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Luana Bach', 'luana.deolinda@unidasul.com.br', 'Controladoria', 'Contabilidade', 'Consulta de notas fiscais de energia e água', 'Workshop I', array['Financeiro', 'Contablidade', 'Compliance']::text[], 'Diário', '1 a 3 Vezes', 'De 1 a 2 horas', 'De 2 a 4 pessoas', 'rpa'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'diario'::frequency_bucket, 4, 'medio'::fte_bucket, 99, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"nao","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":4,"eliminacaoErros":4,"produtividade":4,"qualidadeDados":4,"reducaoCustos":4,"reducaoRetrabalho":4,"compliance":4,"objetivosEstrategicos":4}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Luana Bach', 'luana.deolinda@unidasul.com.br', 'Controladoria', 'Contabilidade', 'Conferência das notas de issqn das nota emitidas para Unidasul', 'Workshop I', array['Contablidade', 'Financeiro', 'Compliance']::text[], 'Semanal', 'Acima de 20 Vezes', 'De 1 a 2 horas', 'De 2 a 4 pessoas', 'rpa'::automation_tool, 'alto'::effort_level, 'baixo'::complexity_level, 'semanal'::frequency_bucket, 4, 'baixo'::fte_bucket, 19.3, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"nao","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":4,"eliminacaoErros":4,"produtividade":4,"qualidadeDados":4,"reducaoCustos":4,"reducaoRetrabalho":4,"compliance":4,"objetivosEstrategicos":4}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Bruna Rodrigues de Matos', 'Bruna.Rodrigues@unidasul.com.br', 'RH', 'Treinamento e Desenvolvimento', 'Tabulação avaliações de treinamento', 'Workshop I', array['Recursos Humanos', 'Operacional', 'Treinamento']::text[], 'Semanal', '1 a 3 Vezes', 'De 1 a 2 horas', 'De 2 a 4 pessoas', 'rpa'::automation_tool, 'alto'::effort_level, 'baixo'::complexity_level, 'semanal'::frequency_bucket, 4, 'baixo'::fte_bucket, 19.3, '{"causaReclamacoes":"nao","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"nao","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":3,"eliminacaoErros":4,"produtividade":3,"qualidadeDados":5,"reducaoCustos":3,"reducaoRetrabalho":3,"compliance":3,"objetivosEstrategicos":4}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Elisiane Pedroso da Luz', 'elisiane.pedroso@unidasul.com.br', 'Financeiro', 'Contas a Receber', 'Recarga - Cartão Convênio Pra TI', 'Workshop I', array['Operacional', 'Financeiro', 'Contablidade']::text[], 'Semanal', '1 a 3 Vezes', 'De 1 a 2 horas', '1 Pessoa', 'rpa'::automation_tool, 'alto'::effort_level, 'baixo'::complexity_level, 'semanal'::frequency_bucket, 5, 'muito_baixo'::fte_bucket, 6.4, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"nao","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":5,"produtividade":5,"qualidadeDados":5,"reducaoCustos":3,"reducaoRetrabalho":5,"compliance":5,"objetivosEstrategicos":5}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Luana simphronio de Mello', 'luana.mello@unidasul.com.br', 'Contas a pagar', 'Financeiro', 'Encontro de contas de fornecedores  devoluções e verbas', 'Workshop I', array['Financeiro', 'Operacional', 'Gestão de Processo']::text[], 'Diário', 'Acima de 20 Vezes', '1 dia (Até 8 horas)', '1 Pessoa', 'ambos'::automation_tool, 'alto'::effort_level, 'alto'::complexity_level, 'diario'::frequency_bucket, 4, 'alto'::fte_bucket, 176, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"sim","padronizacaoDocs":"nao","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":4,"eliminacaoErros":4,"produtividade":4,"qualidadeDados":4,"reducaoCustos":4,"reducaoRetrabalho":4,"compliance":4,"objetivosEstrategicos":4}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Patricia Brehm Loreto', 'patricia.brehm@unidasul.com.br', 'Depto Pessoal', 'Depto Pessoal', 'Admissão Rescisão Notas Fiscais  líquido bancários  contabilização importação de planilhas rateio', 'Workshop I', array['Depto Pessoal', 'Operacional', 'Financeiro']::text[], 'Diário', '9 a 15 Vezes', '1 dia (Até 8 horas)', '1 Pessoa', 'rpa'::automation_tool, 'alto'::effort_level, 'alto'::complexity_level, 'diario'::frequency_bucket, 4, 'alto'::fte_bucket, 176, '{"causaReclamacoes":"sim","totalmenteManual":"parcial","regrasClaras":"sim","decisaoHumana":"sim","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":4,"eliminacaoErros":3,"produtividade":4,"qualidadeDados":4,"reducaoCustos":5,"reducaoRetrabalho":5,"compliance":4,"objetivosEstrategicos":4}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Daniela', 'daniela.gallas@unidasul.com.br', 'Departamento pessoal', 'Departamento pessoal', 'Admissão, rescisão, notas fiscais, líquido bancário, contabizacao, importação de planilha em Excel e CSV.', 'Workshop I', array['Departamento pessoal', 'Operacional', 'Financeiro']::text[], 'Diário', '9 a 15 Vezes', '1 dia (Até 8 horas)', '1 Pessoa', 'rpa'::automation_tool, 'alto'::effort_level, 'alto'::complexity_level, 'diario'::frequency_bucket, 4, 'alto'::fte_bucket, 176, '{"causaReclamacoes":"sim","totalmenteManual":"parcial","regrasClaras":"sim","decisaoHumana":"sim","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":4,"eliminacaoErros":3,"produtividade":4,"qualidadeDados":4,"reducaoCustos":5,"reducaoRetrabalho":5,"compliance":4,"objetivosEstrategicos":5}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Giselly', 'giselly.morcelli@unidasul.com.br', 'Pessoas e Cultura', 'Recrutamento e Seleção', 'Indicadores BI de processos de Recrutamento e Seleção, Criação de Postos de trabalho, atualização de cargos/ tabelas salariais/ hierarquia e outros que ainda precisam ser mapeados', 'Workshop I', array['Recursos Humanos', 'Operacional', 'Planejamento Estratégico']::text[], 'Semanal', '4 a 8 Vezes', 'De 3 a 4 horas', 'De 2 a 4 pessoas', 'rpa'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'semanal'::frequency_bucket, 4, 'medio'::fte_bucket, 45.1, '{"causaReclamacoes":"sim","totalmenteManual":"parcial","regrasClaras":"sim","decisaoHumana":"sim","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":4,"eliminacaoErros":4,"produtividade":4,"qualidadeDados":5,"reducaoCustos":4,"reducaoRetrabalho":5,"compliance":4,"objetivosEstrategicos":4}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Bruno Martin', 'bruno.martins@unidasul.com.br', 'Controladoria', 'Patrimônio', 'Transferências de centro de custo do ativo imobilizado', 'Workshop I', array['Contablidade', 'Gestão de Processo', 'Planejamento Estratégico']::text[], 'Diário', '1 a 3 Vezes', 'De 1 a 2 horas', '1 Pessoa', 'rpa'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'diario'::frequency_bucket, 4, 'baixo'::fte_bucket, 33, '{"causaReclamacoes":"sim","totalmenteManual":"parcial","regrasClaras":"sim","decisaoHumana":"sim","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":3,"eliminacaoErros":4,"produtividade":4,"qualidadeDados":4,"reducaoCustos":3,"reducaoRetrabalho":3,"compliance":3,"objetivosEstrategicos":4}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Lislaine', 'lislaine.teresinha@unidasul.com.br', 'Financeira', 'Tesouraria', 'Boletos correspondente bancário', 'Workshop I', array['Operacional', 'Financeiro', 'Contablidade']::text[], 'Diário', '1 a 3 Vezes', 'De 1 a 2 horas', '1 Pessoa', 'rpa'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'diario'::frequency_bucket, 4, 'baixo'::fte_bucket, 33, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"sim","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":5,"produtividade":5,"qualidadeDados":5,"reducaoCustos":2,"reducaoRetrabalho":5,"compliance":2,"objetivosEstrategicos":5}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Elisiane', 'elisiane.pedroso@unidasul.com.br', 'Financeiro', 'Contas a Receber', 'Bancos', 'Workshop I', array['Operacional', 'Financeiro', 'Backoffice']::text[], 'Diário', '1 a 3 Vezes', 'De 1 a 2 horas', '1 Pessoa', 'rpa'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'diario'::frequency_bucket, 4, 'baixo'::fte_bucket, 33, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"sim","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":3,"produtividade":5,"qualidadeDados":5,"reducaoCustos":3,"reducaoRetrabalho":3,"compliance":3,"objetivosEstrategicos":5}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Lislaine', 'lislaine.teresinha@unidasul.com.br', 'Financeiro', 'Tesouraria', 'Depósito recicladoras', 'Workshop I', array['Operacional', 'Financeiro', 'Contablidade']::text[], 'Diário', '1 a 3 Vezes', 'De 1 a 2 horas', '1 Pessoa', 'rpa'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'diario'::frequency_bucket, 4, 'baixo'::fte_bucket, 33, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"sim","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":5,"produtividade":5,"qualidadeDados":5,"reducaoCustos":2,"reducaoRetrabalho":5,"compliance":2,"objetivosEstrategicos":5}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Lislaine', 'lislaine.teresinha@unidasul.com.br', 'Financeiro', 'Tesouraria', 'Relatório fluxo de caixa diário', 'Workshop I', array['Operacional', 'Financeiro', 'Planejamento Estratégico']::text[], 'Diário', '1 a 3 Vezes', 'De 1 a 2 horas', '1 Pessoa', 'ambos'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'diario'::frequency_bucket, 4, 'baixo'::fte_bucket, 33, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"sim","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"nao","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":5,"produtividade":5,"qualidadeDados":5,"reducaoCustos":2,"reducaoRetrabalho":5,"compliance":2,"objetivosEstrategicos":5}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Lislaine', 'lislaine.teresinha@unidasul.com.br', 'Financeiro', 'Tesouraria', 'Relatório antecipações diárias', 'Workshop I', array['Operacional', 'Financeiro', 'Suporte e Apoio']::text[], 'Diário', '1 a 3 Vezes', 'De 1 a 2 horas', '1 Pessoa', 'rpa'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'diario'::frequency_bucket, 4, 'baixo'::fte_bucket, 33, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"nao","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"nao","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":5,"produtividade":5,"qualidadeDados":5,"reducaoCustos":2,"reducaoRetrabalho":5,"compliance":2,"objetivosEstrategicos":5}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Lislaine', 'lislaine.tesouraria@unidasul.com.br', 'Financeiro', 'Tesouraria', 'Relatório imobilizado', 'Workshop I', array['Operacional', 'Financeiro', 'Suporte e Apoio']::text[], 'Diário', '1 a 3 Vezes', 'De 1 a 2 horas', '1 Pessoa', 'rpa'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'diario'::frequency_bucket, 4, 'baixo'::fte_bucket, 33, '{"causaReclamacoes":"nao","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"nao","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"nao","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":5,"produtividade":5,"qualidadeDados":5,"reducaoCustos":2,"reducaoRetrabalho":5,"compliance":2,"objetivosEstrategicos":5}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Lislaine Teresinha Trocourt de Jesus', 'lislaine.teresinha@unidasul.com.br', 'Financeiro', 'Tesouraria', 'Conciliação automática pix e-commerce', 'Workshop I', array['Operacional', 'Financeiro', 'Contablidade']::text[], 'Semanal', 'Acima de 20 Vezes', 'De 1 a 2 horas', '1 Pessoa', 'rpa'::automation_tool, 'alto'::effort_level, 'baixo'::complexity_level, 'semanal'::frequency_bucket, 4, 'muito_baixo'::fte_bucket, 6.4, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"sim","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":4,"produtividade":4,"qualidadeDados":4,"reducaoCustos":4,"reducaoRetrabalho":4,"compliance":4,"objetivosEstrategicos":4}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Luana Bach', 'luana.deolinda@unidasul.com.br', 'Controladoria', 'Contabilidade', 'Conciliação transferências entre centros', 'Workshop I', array['Contablidade', 'Compliance', 'Gestão de Processo']::text[], 'Semanal', '1 a 3 Vezes', 'De 1 a 2 horas', '1 Pessoa', 'rpa'::automation_tool, 'alto'::effort_level, 'baixo'::complexity_level, 'semanal'::frequency_bucket, 4, 'muito_baixo'::fte_bucket, 6.4, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"nao","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":4,"eliminacaoErros":4,"produtividade":4,"qualidadeDados":4,"reducaoCustos":4,"reducaoRetrabalho":4,"compliance":4,"objetivosEstrategicos":4}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Augusto Conrado souza', 'augusto.souza@unidasul.com.br', 'SESMT', 'Segurança do trabalho', 'CIPA', 'Workshop I', array['Segurança do trabalho', 'Operacional', 'Jurídico']::text[], 'Anual', '1 a 3 Vezes', 'Processo eleitoral cerca 60 dias', 'Cada filial precisa envolver pessoas no processo', 'rpa'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'anual'::frequency_bucket, 5, 'muito_alto'::fte_bucket, 307.2, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"sim","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"nao"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":5,"produtividade":4,"qualidadeDados":5,"reducaoCustos":3,"reducaoRetrabalho":5,"compliance":5,"objetivosEstrategicos":4}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Anageli', 'Anageli.haupt@unidasul.com.br', 'Financeiro', 'Contas a pagar', 'Baixas de compensações', 'Workshop I', array['Financeiro', 'Operacional', 'Contablidade']::text[], 'Diário', '1 a 3 Vezes', 'De 3 a 4 horas', '1 Pessoa', 'ambos'::automation_tool, 'alto'::effort_level, 'alto'::complexity_level, 'diario'::frequency_bucket, 4, 'medio'::fte_bucket, 77, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"nao","decisaoHumana":"sim","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":4,"eliminacaoErros":4,"produtividade":4,"qualidadeDados":4,"reducaoCustos":4,"reducaoRetrabalho":4,"compliance":4,"objetivosEstrategicos":4}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Elisiane Pedroso da Luz', 'Elisiane.pedroso@unidasul.com.br', 'Financeiro', 'Contas a receber', 'Relatório Banco', 'Workshop I', array['Financeiro', 'Operacional', 'Backoffice']::text[], 'Diário', '1 a 3 Vezes', 'De 1 a 2 horas', '1 Pessoa', 'rpa'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'diario'::frequency_bucket, 3, 'baixo'::fte_bucket, 33, '{"causaReclamacoes":"nao","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"sim","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":4,"eliminacaoErros":4,"produtividade":4,"qualidadeDados":4,"reducaoCustos":2,"reducaoRetrabalho":3,"compliance":2,"objetivosEstrategicos":3}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Lislaine', 'lislaine.teresinha@unidasul.com.br', 'Financeiro', 'Tesouraria', 'Solicitação de troco', 'Workshop I', array['Operacional', 'Financeiro', 'Gestão de Processo']::text[], 'Quinzenal', '1 a 3 Vezes', 'De 3 a 4 horas', 'Totas as tesoureiras das lojas', 'rpa'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'quinzenal'::frequency_bucket, 4, 'medio'::fte_bucket, 56, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"sim","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":5,"produtividade":5,"qualidadeDados":5,"reducaoCustos":2,"reducaoRetrabalho":5,"compliance":2,"objetivosEstrategicos":5}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Lislaine', 'lislaine.teresinha@unidasul.com.br', 'Financeiro', 'Tesouraria', 'Fechamento Recarga Celular', 'Workshop I', array['Financeiro', 'Operacional', 'Planejamento Estratégico']::text[], 'Mensal', '1 a 3 Vezes', 'De 1 a 2 horas', '1 Pessoa', 'rpa'::automation_tool, 'alto'::effort_level, 'baixo'::complexity_level, 'mensal'::frequency_bucket, 5, 'muito_baixo'::fte_bucket, 1.5, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"sim","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":5,"produtividade":5,"qualidadeDados":5,"reducaoCustos":5,"reducaoRetrabalho":5,"compliance":3,"objetivosEstrategicos":5}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Janaína Leandro', 'Janaína.tamara@unidasul.com.br', 'Controladoria', 'Controle & Gestão', 'Registro de Inventário', 'Workshop I', array['Contablidade', 'Operacional', 'Tecnologia da Informação (TI)']::text[], 'Mensal', '1 a 3 Vezes', '1 dia (Até 8 horas)', 'Todas filiais com estoque', 'rpa'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'mensal'::frequency_bucket, 4, 'medio'::fte_bucket, 64, '{"causaReclamacoes":"sim","totalmenteManual":"parcial","regrasClaras":"sim","decisaoHumana":"nao","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":4,"eliminacaoErros":4,"produtividade":4,"qualidadeDados":4,"reducaoCustos":4,"reducaoRetrabalho":4,"compliance":4,"objetivosEstrategicos":4}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Anageli', 'anageli.haupt@unidasul.com.br', 'Financeiro', 'Conta a pagar', 'Identificação de Creditos de fornecedores', 'Workshop I', array['Financeiro', 'Operacional', 'Comercial / Vendas']::text[], 'Diário', '1 a 3 Vezes', 'De 1 a 2 horas', '1 Pessoa', 'rpa'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'diario'::frequency_bucket, 2, 'baixo'::fte_bucket, 33, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"nao","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":2,"produtividade":5,"qualidadeDados":1,"reducaoCustos":1,"reducaoRetrabalho":1,"compliance":1,"objetivosEstrategicos":3}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Maria Salete Kunzler', 'maria.salete@unidasul.com.br', 'Sheila Raupp Bauer', 'Contabilidade', 'Conciliação Vendas e Compras', 'Workshop I', array['Contablidade', 'Operacional', 'Compliance']::text[], 'Mensal', '1 a 3 Vezes', '1 dia (Até 8 horas)', '1 Pessoa', 'rpa'::automation_tool, 'alto'::effort_level, 'baixo'::complexity_level, 'mensal'::frequency_bucket, 4, 'muito_baixo'::fte_bucket, 8, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"sim","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":4,"eliminacaoErros":4,"produtividade":4,"qualidadeDados":4,"reducaoCustos":4,"reducaoRetrabalho":4,"compliance":4,"objetivosEstrategicos":4}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Catia Silva', 'catia.silva@unidasul.com.br', 'Contabilidade', 'Movimento de Caixa', 'Compensação de contas', 'Workshop I', array['Contablidade', 'Operacional', 'Financeiro']::text[], 'Mensal', '1 a 3 Vezes', 'De 1 a 2 horas', '1 Pessoa', 'rpa'::automation_tool, 'alto'::effort_level, 'baixo'::complexity_level, 'mensal'::frequency_bucket, 4, 'muito_baixo'::fte_bucket, 1.5, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"sim","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":4,"eliminacaoErros":4,"produtividade":4,"qualidadeDados":4,"reducaoCustos":4,"reducaoRetrabalho":4,"compliance":4,"objetivosEstrategicos":4}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Catia Silva', 'catia.silva@unidasul.com.br', 'Contabilidade', 'Movimento de Caixa', 'Conciliação Troco', 'Workshop I', array['Operacional', 'Financeiro', 'Contablidade']::text[], 'Mensal', '1 a 3 Vezes', 'De 1 a 2 horas', '1 Pessoa', 'rpa'::automation_tool, 'alto'::effort_level, 'baixo'::complexity_level, 'mensal'::frequency_bucket, 4, 'muito_baixo'::fte_bucket, 1.5, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"nao","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":4,"eliminacaoErros":4,"produtividade":4,"qualidadeDados":4,"reducaoCustos":4,"reducaoRetrabalho":4,"compliance":4,"objetivosEstrategicos":4}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Ana Luisa Jacobs', 'Ana.luisa@unidasul.com.br', 'Financeiro', 'Tesouraria', 'Conciliação Bancária', 'Workshop I', array['Financeiro', 'Operacional', 'Gestão de Processo']::text[], 'Semanal', '1 a 3 Vezes', 'De 3 a 4 horas', '1 Pessoa', 'ambos'::automation_tool, 'medio'::effort_level, 'medio'::complexity_level, 'semanal'::frequency_bucket, 4, 'baixo'::fte_bucket, 15, '{"causaReclamacoes":"nao","totalmenteManual":"parcial","regrasClaras":"sim","decisaoHumana":"sim","padronizacaoDocs":"nao","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":4,"eliminacaoErros":4,"produtividade":4,"qualidadeDados":4,"reducaoCustos":4,"reducaoRetrabalho":4,"compliance":4,"objetivosEstrategicos":4}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Lislaine', 'lislaine.teresinha@unidasul.com.br', 'Financeiro', 'Tesouraria', 'Relatório fluxo de caixa previsto', 'Workshop I', array['Operacional', 'Financeiro', 'Planejamento Estratégico']::text[], 'Semanal', '1 a 3 Vezes', 'De 3 a 4 horas', '1 Pessoa', 'rpa'::automation_tool, 'alto'::effort_level, 'alto'::complexity_level, 'semanal'::frequency_bucket, 4, 'baixo'::fte_bucket, 15, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"sim","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":5,"produtividade":5,"qualidadeDados":5,"reducaoCustos":2,"reducaoRetrabalho":5,"compliance":2,"objetivosEstrategicos":5}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Rudney Pâncaro Moscarelli Filho', 'rudney.filho@unidasul.com.br', 'Controladoria', 'Controle e Gestão', 'Controladoria analítica', 'Workshop I', array['Planejamento Estratégico', 'Operacional', 'Contablidade']::text[], 'Mensal', '1 a 3 Vezes', 'De 1 a 2 horas', 'De 2 a 4 pessoas', 'ambos'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'mensal'::frequency_bucket, 5, 'muito_baixo'::fte_bucket, 4.5, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"sim","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"nao","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":5,"produtividade":5,"qualidadeDados":5,"reducaoCustos":5,"reducaoRetrabalho":5,"compliance":3,"objetivosEstrategicos":5}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Janaína Leandro', 'Janaína.tamara@hotmail.com', 'Controladoria', 'controle e gestão', 'Metas compradores atacado e varejo', 'Workshop I', array['Comercial / Vendas', 'Contablidade', 'Compras / Suprimento']::text[], 'Mensal', '1 a 3 Vezes', 'De 3 a 4 horas', 'De 2 a 4 pessoas', 'rpa'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'mensal'::frequency_bucket, 4, 'baixo'::fte_bucket, 10.5, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"sim","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":4,"eliminacaoErros":4,"produtividade":4,"qualidadeDados":4,"reducaoCustos":4,"reducaoRetrabalho":4,"compliance":4,"objetivosEstrategicos":4}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Janaina Leandro', 'Janaina.tamara@unidasul.com.br', 'Controladoria', 'Controle & Gestão', 'Faturamento mensal filiais para gestão aluguéis/envio locatário', 'Workshop I', array['Operacional', 'Contablidade', 'Diretoria expansão']::text[], 'Mensal', '1 a 3 Vezes', 'De 3 a 4 horas', '1 Pessoa', 'rpa'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'mensal'::frequency_bucket, 4, 'muito_baixo'::fte_bucket, 3.5, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"nao","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"nao","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":4,"eliminacaoErros":4,"produtividade":4,"qualidadeDados":4,"reducaoCustos":4,"reducaoRetrabalho":4,"compliance":4,"objetivosEstrategicos":4}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Catia Silva', 'catia.silva@unidasul.com.br', 'Contabilidade', 'Movimento de Caixa', 'Conciliação depósito', 'Workshop I', array['Operacional', 'Financeiro', 'Contablidade']::text[], 'Mensal', '1 a 3 Vezes', 'De 1 a 2 horas', '1 Pessoa', 'rpa'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'mensal'::frequency_bucket, 4, 'muito_baixo'::fte_bucket, 1.5, '{"causaReclamacoes":"sim","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"nao","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":4,"eliminacaoErros":4,"produtividade":4,"qualidadeDados":4,"reducaoCustos":4,"reducaoRetrabalho":4,"compliance":4,"objetivosEstrategicos":4}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Lislaine', 'lislaine.teresinha@unidasul.com.br', 'Financeiro', 'Tesouraria', 'Importação do extratos bancários', 'Workshop I', array['Operacional', 'Financeiro', 'Contablidade']::text[], 'Mensal', '1 a 3 Vezes', 'De 1 a 2 horas', '1 Pessoa', 'rpa'::automation_tool, 'alto'::effort_level, 'medio'::complexity_level, 'mensal'::frequency_bucket, 4, 'muito_baixo'::fte_bucket, 1.5, '{"causaReclamacoes":"nao","totalmenteManual":"sim","regrasClaras":"sim","decisaoHumana":"nao","padronizacaoDocs":"sim","validacaoDados":"sim","schedulable":"sim","temDocumentacao":"sim"}'::jsonb, '{"reducaoTempo":5,"eliminacaoErros":5,"produtividade":5,"qualidadeDados":2,"reducaoCustos":2,"reducaoRetrabalho":5,"compliance":2,"objetivosEstrategicos":5}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid),
    ('55551da5-0000-0000-0000-000000000001'::uuid, 'formulario'::opportunity_source, 'Joel Pereira', 'joel.pereira@unidasul.com.br', 'Segurança do Trabalho', 'DP', 'Criação de PGRs', 'Workshop I', array['Operacional', 'DP', 'Recursos Humanos']::text[], 'Mensal', 'Acima de 20 Vezes', '1 dia (Até 8 horas)', '2', 'ambos'::automation_tool, 'medio'::effort_level, 'medio'::complexity_level, 'mensal'::frequency_bucket, 4, 'baixo'::fte_bucket, 16, '{"causaReclamacoes":"sim","totalmenteManual":"parcial","regrasClaras":"sim","decisaoHumana":"nao","padronizacaoDocs":"nao","validacaoDados":"nao","schedulable":"nao","temDocumentacao":"nao"}'::jsonb, '{"reducaoTempo":4,"eliminacaoErros":4,"produtividade":4,"qualidadeDados":4,"reducaoCustos":4,"reducaoRetrabalho":4,"compliance":4,"objetivosEstrategicos":4}'::jsonb, null, 'novo'::opportunity_status, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid)
    ;
  end if;
end $$;

-- =============================================================================
-- 5. Verificação rápida (descomente após rodar — ver também o HANDOFF):
-- =============================================================================
-- select count(*) from opportunities o join tenants t on t.id = o.tenant_id
--   where t.slug = 'unidasul';   -- esperado: 64

-- =============================================================================
-- FIM 0013 — Tenant + admin Unidasul + 64 oportunidades do Workshop I
-- =============================================================================
